insert into materia values 
('FIS','Física'),
('MAT','Matemáticas'),
('QUI','Química'),
('CAL1','Calculo I'),
('CAL2','Calculo II'),
('CAL3','Calculo III'),
('ALG1','Algebra I'),
('ALG2','Algebra II'),
('FIS_GEN','Fisica General'),
('FIS1','Fisica I'),
('FIS2','Fisica II'),
('FIS3','Fisica III'),
('QUI1','Quimica I'),
('QUI2','Química II');